<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUG58Mek\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUG58Mek/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUG58Mek.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUG58Mek\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUG58Mek\App_KernelDevDebugContainer([
    'container.build_hash' => 'UG58Mek',
    'container.build_id' => 'ba444a88',
    'container.build_time' => 1699886537,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUG58Mek');
